substitutions:
  name: "everything-presence-pro"
  friendly_name: "Everything Presence Pro"
  hidden_ssid: "false"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"
  log_level: "DEBUG"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

packages:
   pro_base: !include common/everything-presence-pro-base.yaml
   ld2450_base: !include common/ld2450-base.yaml
   sen0609_base: !include common/sen0609-base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True

# wifi:
#   ssid: Everything Smart IoT
#   ***REDACTED***

#   # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "Dual-Mmwave Fallback Hotspot"
#     password: "mVZVN2Aoc9Vd"
