substitutions:
  name: "everything-presence-pro"
  friendly_name: "Everything Presence Pro"
  hidden_ssid: "false"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"
  log_level: "DEBUG"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

packages:
   pro_base: !include common/everything-presence-pro-base.yaml
   ld2450_base: !include common/ld2450-base.yaml
   sen0609_base: !include common/sen0609-base.yaml
   bluetooth_base: !include common/bluetooth-base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  on_boot:
    - priority: -100
      then:
        - lambda: |-
            id(firmware_network).publish_state("WiFi");
            id(firmware_co2).publish_state("Disabled");
            id(firmware_ble).publish_state("Enabled");

update:
  - platform: http_request
    id: update_http_request
    name: Firmware Update
    source: https://docs.everythingsmart.io/update/everything-presence-pro/everything-presence-pro-wifi-ble-manifest.json

wifi:
  on_connect:
    then:
      - if:
          condition:
            lambda: 'return !id(api_connected_flag) && id(led_mode_select).state != "Manual Control";'
          then:
            - light.turn_on:
                id: led_rgb
                brightness: 40%
                red: 0%
                green: 100%
                blue: 0%
                white: 0%
                effect: "Pulse"
            - delay: 800ms
            # Return to loading animation until API connects
            - light.turn_on:
                id: led_rgb
                brightness: 25%
                red: 100%
                green: 80%
                blue: 0%
                white: 0%
                effect: "Network Connecting"

  on_disconnect:
    then:
      - if:
          condition:
            lambda: 'return !id(api_connected_flag) && id(led_mode_select).state != "Manual Control";'
          then:
            - light.turn_on:
                id: led_rgb
                brightness: 25%
                red: 100%
                green: 80%
                blue: 0%
                white: 0%
                effect: "Network Connecting"

esp32_improv:
  authorizer: none
