substitutions:
  name: "everything-presence-pro"
  friendly_name: "Everything Presence Pro"
  hidden_ssid: "false"
  factory_reset_disabled: "true"
  uart_target_output_disabled: "true"
  uart_presence_output_disabled: "true"
  log_level: "DEBUG"
  # Firmware variant configuration
  firmware_network: "WiFi"
  firmware_co2: "Disabled"
  firmware_ble: "Disabled"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended

packages:
   pro_base: !include common/everything-presence-pro-base.yaml
   ld2450_base: !include common/ld2450-base.yaml
   sen0609_base: !include common/sen0609-base.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True

update:
  - platform: http_request
    name: Firmware Update
    source: https://everythingsmarthome.github.io/everything-presence-pro/everything-presence-pro-wifi-manifest.json

wifi:
  ap:
    ssid: "Everything Presence Pro"

captive_portal:

improv_serial:
