sensor:
  - platform: scd4x
    i2c_id: bus_b
    id: scd40
    co2:
      name: "CO2"
      id: "co2"
      on_value:
        then:
          - if:
              condition:
                lambda: 'return id(led_mode_select).state == "Environmental" || id(led_mode_select).state == "Environmental + Presence";'
              then:
                - script.execute: control_leds
    automatic_self_calibration: false

i2c:
  - id: bus_b
    scl: GPIO16
    sda: GPIO4
    scan: true

button:
  - platform: template
    name: "Calibrate CO2"
    id: calibrate_scd40
    on_press:
      - scd4x.perform_forced_calibration:
          value: 419
          id: scd40

select:
  # Override LED Mode selector to add Environmental options for CO2 builds
  - platform: template
    name: "LED Mode"
    id: led_mode_select
    entity_category: config
    optimistic: true
    options:
      - "Manual Control"
      - "Environmental"
      - "Presence"
      - "Environmental + Presence"
    initial_option: "Manual Control"
    restore_value: true
    icon: mdi:led-variant
    on_value:
      then:
        - script.execute: control_leds

script:
  # Override the placeholder control_leds_environmental_presence from base config
  - id: control_leds_environmental_presence
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(occupancy).state;'
          then:
            # Presence detected - check CO2 level
            - if:
                condition:
                  # CO2 is good - just show presence
                  lambda: 'return id(co2).state < 800;'
                then:
                  # Good CO2 - show steady presence glow (warm purple)
                  - light.turn_on:
                      id: led_rgb
                      effect: none
                  - delay: 50ms
                  - light.turn_on:
                      id: led_rgb
                      brightness: !lambda 'return 0.55 * id(led_brightness_multiplier).state;'
                      red: 80%
                      green: 20%
                      blue: 100%
                      white: 0%
                      transition_length: 600ms
                  - delay: 650ms
                  - light.turn_on:
                      id: led_rgb
                      effect: "Presence Glow"
                else:
                  # CO2 is elevated (warning or alert) - alternate between presence and environmental
                  - script.execute: alternate_presence_environmental
          else:
            # No presence - show environmental status only
            - script.execute: update_environmental_led

  # Override the placeholder alternate_presence_environmental from base config
  - id: alternate_presence_environmental
    mode: restart
    then:
      # Show presence glow (warm purple) for 3 seconds
      - light.turn_on:
          id: led_rgb
          effect: none
      - delay: 50ms
      - light.turn_on:
          id: led_rgb
          brightness: !lambda 'return 0.55 * id(led_brightness_multiplier).state;'
          red: 80%
          green: 20%
          blue: 100%
          white: 0%
          transition_length: 600ms
      - delay: 650ms
      - light.turn_on:
          id: led_rgb
          effect: "Presence Glow"
      - delay: 3000ms
      # Transition to environmental status for 4 seconds
      - if:
          condition:
            lambda: 'return id(co2).state >= 800 && id(co2).state < 1200;'
          then:
            # Warning level - amber
            - light.turn_on:
                id: led_rgb
                effect: none
            - delay: 50ms
            - light.turn_on:
                id: led_rgb
                brightness: !lambda 'return 0.45 * id(led_brightness_multiplier).state;'
                red: 100%
                green: 65%
                blue: 0%
                white: 0%
                transition_length: 600ms
            - delay: 650ms
            - light.turn_on:
                id: led_rgb
                effect: "Environmental Warning"
      - if:
          condition:
            lambda: 'return id(co2).state >= 1200;'
          then:
            # Alert level - red
            - light.turn_on:
                id: led_rgb
                effect: none
            - delay: 50ms
            - light.turn_on:
                id: led_rgb
                brightness: !lambda 'return 0.55 * id(led_brightness_multiplier).state;'
                red: 100%
                green: 0%
                blue: 0%
                white: 0%
                transition_length: 600ms
            - delay: 650ms
            - light.turn_on:
                id: led_rgb
                effect: "Environmental Alert"
      - delay: 4000ms
      # Loop back by calling control_leds if still in this mode
      - if:
          condition:
            lambda: 'return id(led_mode_select).state == "Environmental + Presence" && id(occupancy).state && id(co2).state >= 800;'
          then:
            - script.execute: alternate_presence_environmental

  # Override the placeholder update_environmental_led from base config
  - id: update_environmental_led
    mode: restart
    then:
      # Check CO2 levels and update LED accordingly
      - if:
          condition:
            lambda: 'return id(co2).state >= 1200;'
          then:
            # High CO2 - red with alert effect
            - light.turn_on:
                id: led_rgb
                effect: none
            - delay: 50ms
            - light.turn_on:
                id: led_rgb
                brightness: !lambda 'return 0.55 * id(led_brightness_multiplier).state;'
                red: 100%
                green: 0%
                blue: 0%
                white: 0%
                transition_length: 600ms
            - delay: 650ms
            - light.turn_on:
                id: led_rgb
                effect: "Environmental Alert"
          else:
            - if:
                condition:
                  lambda: 'return id(co2).state >= 800;'
                then:
                  # Medium CO2 - amber with warning effect
                  - light.turn_on:
                      id: led_rgb
                      effect: none
                  - delay: 50ms
                  - light.turn_on:
                      id: led_rgb
                      brightness: !lambda 'return 0.45 * id(led_brightness_multiplier).state;'
                      red: 100%
                      green: 65%
                      blue: 0%
                      white: 0%
                      transition_length: 600ms
                  - delay: 650ms
                  - light.turn_on:
                      id: led_rgb
                      effect: "Environmental Warning"
                else:
                  # Good CO2 - steady green (no effect)
                  - light.turn_on:
                      id: led_rgb
                      effect: none
                  - delay: 50ms
                  - light.turn_on:
                      id: led_rgb
                      brightness: !lambda 'return 0.35 * id(led_brightness_multiplier).state;'
                      red: 0%
                      green: 100%
                      blue: 0%
                      white: 0%
                      transition_length: 600ms

