globals:
  - id: dfrobot_factory_resetting
    type: bool
    initial_value: 'false'

binary_sensor:
  - platform: gpio
    name: Static Presence
    id: dfrobot_presence
    device_class: occupancy
    pin:
      number: GPIO34

switch:
  - platform: template
    name: Static Presence Sensor Enable
    id: dfrobot_sensor
    disabled_by_default: False
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    turn_on_action:
      - uart.write:
          id: uart_bus_dfrobot
          data: "sensorStart\r\n"
      - delay: 1s
    turn_off_action:
      - uart.write:
          id: uart_bus_dfrobot
          data: "sensorStop\r\n"
      - delay: 1s

  - platform: template
    name: Static Presence Debug Output
    id: dfrobot_uart_presence
    entity_category: config
    disabled_by_default: true
    optimistic: true
    turn_on_action:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "setUartOutput 1 1\r\n"
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 3s
      - switch.turn_on: dfrobot_sensor
    turn_off_action:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "setUartOutput 1 0\r\n"
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 3s
      - switch.turn_on: dfrobot_sensor

  - platform: template
    name: Static Presence Target Output
    id: dfrobot_uart_target
    entity_category: config
    disabled_by_default: true
    optimistic: true
    assumed_state: false
    turn_on_action:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "setUartOutput 2 1 1 1\r\n"
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 3s
      - switch.turn_on: dfrobot_sensor
    turn_off_action:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "setUartOutput 2 0\r\n"
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 3s
      - switch.turn_on: dfrobot_sensor

number:
  - platform: template
    id: dfrobot_min_distance
    name: Static Presence Min Range
    icon: mdi:arrow-left-right
    entity_category: config
    min_value: 0.6
    max_value: 25
    initial_value: 0.6
    optimistic: true
    step: 0.1
    restore_value: true
    unit_of_measurement: m
    mode: slider

  - platform: template
    id: dfrobot_max_distance
    name: Static Presence Max Range
    icon: mdi:arrow-left-right
    entity_category: config
    min_value: 0.6
    max_value: 25
    initial_value: 6
    optimistic: true
    step: 0.1
    restore_value: true
    unit_of_measurement: m
    mode: slider

  - platform: template
    name: Static Presence Trigger Range
    icon: mdi:radar
    id: dfrobot_trigger_distance
    entity_category: config
    min_value: 0
    max_value: 25
    initial_value: 6
    optimistic: true
    step: 0.1
    restore_value: true
    unit_of_measurement: m
    mode: slider
    set_action:
      - if:
          condition:
            lambda: 'return !id(dfrobot_factory_resetting);'
          then:
            - switch.turn_off: dfrobot_sensor
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: !lambda |-
                  auto ms = str_sprintf("setTrigRange %.1f\r\n", x);
                  return std::vector<unsigned char>(ms.begin(), ms.end());
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: "saveConfig\r\n"
            - delay: 1s
            - switch.turn_on: dfrobot_sensor

  - platform: template
    name: Static Presence Timeout
    icon: mdi:clock-end
    entity_category: config
    id: dfrobot_off_delay
    min_value: 10
    max_value: 600
    initial_value: 15
    optimistic: true
    step: 5
    restore_value: true
    unit_of_measurement: seconds
    mode: slider
    set_action:
      - if:
          condition:
            lambda: 'return !id(dfrobot_factory_resetting);'
          then:
            - switch.turn_off: dfrobot_sensor
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: !lambda |-
                  auto ms = str_sprintf("setLatency %.2f %.0f\r\n", id(dfrobot_on_delay).state, id(dfrobot_off_delay).state);
                  return std::vector<unsigned char>(ms.begin(), ms.end());
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: "saveConfig\r\n"
            - delay: 1s
            - switch.turn_on: dfrobot_sensor

  - platform: template
    name: Static Presence On Delay
    icon: mdi:clock-start
    id: dfrobot_on_delay
    entity_category: config
    min_value: 0
    max_value: 2
    initial_value: 0
    optimistic: true
    step: 0.25
    restore_value: true
    unit_of_measurement: seconds
    mode: slider
    set_action:
      - if:
          condition:
            lambda: 'return !id(dfrobot_factory_resetting);'
          then:
            - switch.turn_off: dfrobot_sensor
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: !lambda |-
                  auto ms = str_sprintf("setLatency %.2f %.0f\r\n", id(dfrobot_on_delay).state, id(dfrobot_off_delay).state);
                  return std::vector<unsigned char>(ms.begin(), ms.end());
            - delay: 1s
            - uart.write:
                id: uart_bus_dfrobot
                data: "saveConfig\r\n"
            - delay: 1s
            - switch.turn_on: dfrobot_sensor

  - platform: template
    name: Static Presence Sustain Sensitivity
    icon: mdi:target-variant
    id: dfrobot_sustain_sensitivity
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 7
    optimistic: true
    step: 1
    restore_value: true

  - platform: template
    name: Static Presence Trigger Sensitivity
    icon: mdi:target-variant
    id: dfrobot_trigger_sensitivity
    entity_category: config
    min_value: 0
    max_value: 9
    initial_value: 5
    optimistic: true
    step: 1
    restore_value: true

button:
  - platform: template
    name: "Apply Static Range Settings"
    id: set_dfrobot_distance
    entity_category: config
    on_press:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: !lambda |-
            auto ms = str_sprintf("setRange %.1f %.1f\r\n", id(dfrobot_min_distance).state, id(dfrobot_max_distance).state);
            return std::vector<unsigned char>(ms.begin(), ms.end());
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 1s
      - switch.turn_on: dfrobot_sensor
 
  - platform: template
    name: "Apply Static Sensitivity Settings"
    id: set_dfrobot_sensitivity
    entity_category: config
    on_press:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: !lambda |-
            auto ms = str_sprintf("setSensitivity %d %d\r\n", (int)id(dfrobot_sustain_sensitivity).state, (int)id(dfrobot_trigger_sensitivity).state);
            return std::vector<unsigned char>(ms.begin(), ms.end());
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 1s
      - switch.turn_on: dfrobot_sensor

  - platform: template
    name: Restart Static Presence Sensor
    id: restart_dfrobot
    entity_category: config
    internal: true
    on_press:
      - uart.write:
          id: uart_bus_dfrobot
          data: "resetSystem\r\n"

  - platform: template
    name: Factory Reset Static Presence Sensor
    icon: mdi:cog-counterclockwise
    id: factory_reset_dfrobot
    disabled_by_default: true
    entity_category: config
    on_press:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "resetCfg\r\n"
      - delay: 3s
      # Set flag to prevent set_actions from sending commands during reset
      - globals.set:
          id: dfrobot_factory_resetting
          value: 'true'
      # Reset all entity values to factory defaults
      - number.set:
          id: dfrobot_min_distance
          value: 0.6
      - number.set:
          id: dfrobot_max_distance
          value: 6
      - number.set:
          id: dfrobot_trigger_distance
          value: 6
      - number.set:
          id: dfrobot_sustain_sensitivity
          value: 7
      - number.set:
          id: dfrobot_trigger_sensitivity
          value: 5
      - number.set:
          id: dfrobot_on_delay
          value: 0
      - number.set:
          id: dfrobot_off_delay
          value: 15
      # Clear the flag
      - globals.set:
          id: dfrobot_factory_resetting
          value: 'false'
      - switch.turn_on: dfrobot_sensor

light:
  - platform: binary
    name: Static Presence LED
    restore_mode: RESTORE_DEFAULT_OFF
    output: dfrobot_led_output
    entity_category: config
    disabled_by_default: False

output:
  - platform: template
    id: dfrobot_led_output
    type: binary
    write_action:
      - switch.turn_off: dfrobot_sensor
      - delay: 1s
      - if:
          condition:
            lambda: !lambda return state;
          then:
            - uart.write:
                id: uart_bus_dfrobot
                data: "setLedMode 1 0\r\n"
          else:
            - uart.write:
                id: uart_bus_dfrobot
                data: "setLedMode 1 1\r\n"
      - delay: 1s
      - uart.write:
          id: uart_bus_dfrobot
          data: "saveConfig\r\n"
      - delay: 3s
      - switch.turn_on: dfrobot_sensor

uart:
  - id: uart_bus_dfrobot
    tx_pin:
      number: GPIO5
      ignore_strapping_warning: true
    rx_pin:
      number: GPIO15
      ignore_strapping_warning: true
    rx_buffer_size: 512
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: true
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);